## Quick Introduction to TFLearn - Exercises

This will be an implementation for a single record only (single example in the dataset).

**Emmanuel Dufourq** (edufourq@gmail.com - www.emmanueldufourq.com)

July 2018

*Made for the Theoretical Foundations of Data Science 2018 (African Institute for Mathematical Sciences)*

Adapted from https://github.com/tflearn/tflearn/blob/master/examples/images/convnet_mnist.py

## TFlearn

Documentation: http://tflearn.org

TFLearn, similar to Keras, is a high-level wrapper to Tensorflow. We can build neural networks and other types of networks using TFLearn.

There are a lot of examples of how to implement networks using TFLearn here: http://tflearn.org/examples/

## Check if a GPU has been allocated

Remmeber to request for GPU acceleration by clicking on Edit > Notebook Settings > Select GPU as "hardware accelerator".

The output of the following code should be: Found GPU at: /device:GPU:0

In [ ]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


## We will need to install TFLearn as it is not installed on Colab by default.

In [ ]:
!pip install tflearn

    100% |████████████████████████████████| 102kB 3.1MB/s 
  Running setup.py bdist_wheel for tflearn ... - \ done
  Stored in directory: /content/.cache/pip/wheels/d0/f6/69/0ef3ee395aac2e5d15d89efd29a9a216f3c27767b43b72c006
Successfully built tflearn


## Imports

In [ ]:
import tflearn
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.normalization import local_response_normalization
from tflearn.layers.estimator import regression

## Import the MNIST dataset from TFLearn

In [ ]:
import tflearn.datasets.mnist as mnist

## Load the data and specify that we want the classes to be in their one-hot encoded form

In [ ]:
X, Y, testX, testY = mnist.load_data(one_hot=True)


Succesfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting mnist/train-images-idx3-ubyte.gz
Succesfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting mnist/train-labels-idx1-ubyte.gz
Succesfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting mnist/t10k-images-idx3-ubyte.gz
Succesfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting mnist/t10k-labels-idx1-ubyte.gz


## Task: check the shape of the data

In [ ]:
None

(55000, 784)

In [ ]:
None

(55000, 10)

## Question: have a look at the shape of X.

Can we apply a CNN to this as it is right now or do we need to reshape the data? What should the shape of an image be when we are considering a CNN?

## Task: have a look at a few Y values are indeed in their one-hot encoded form

In [ ]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [ ]:
None

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Reshape the X values such that they are more suitable for a CNN

In [ ]:
X = X.reshape([-1, 28, 28, 1])

## Task: reshape the X test variable such that it is in a suitable shape for a CNN

In [ ]:
testX = testX.reshape([-1, None, None, None])

## Define a CNN architecture

**We can create an input layer as follows: **

`network = input_data(shape=[None, 28, 28, 1], name='input')`

Here we are telling the package that it should expect a number of images - hence the keyword None - and that the shape of each image is 28x28x1. Here the MNIST dataset consits of 28x28 pixel images and since the data is greyscale the number of channels is set to 1.

**For example, we can create a convolutional layer as follows:**

`network = conv_2d(network, 32, 3, activation='relu')`

Here we are adding a 2D convolutional layer with 32 filters. Each filter is of size 3x3 and we are telling it to use the ReLU activation.

**For example, we  can create a max pooling layer as follows:**

`network = max_pool_2d(network, 3)`

Here we are adding a 2D max pooling layer of which each kernel is of size 3x3.

**For example, we  can add a fully conencted layer as follows:**

`network = fully_connected(network, 32, activation='tanh')`

Here we are adding a fully connected layer of which there are 32 units. We are telling it to use the tanh activation function.

**For example, we  can add dropout as follows:**

`network = dropout(network, 0.8)`

Here we are adding dropout with a keep probability of 0.8

In a similar way to Keras needing the user to specify the .compile() function, in TFLearn we must specify something equivalent.



```
network = regression(network, optimizer='adam', learning_rate=0.01,
                     loss=None, name='target')
```

Here we are telling it to using the adam optimiser, with a learning rate of 0.01.

Task: which loss function should we use? Find a suitable one here: http://tflearn.org/objectives/





Remember, when you create multiple models, or, re-execute your models you should reset the graph so that they don't get mixed up. One way to do this: `tf.reset_default_graph()`. Add this piece of code below

In [ ]:
tf.reset_default_graph()

## Task:

In [ ]:
def cnn_model():

  # Input layer
  network = None

  # Convolutional layer
  network = None

  # Max pooling layer
  network = None

   # Convolutional layer
  network = None

  # Max pooling layer
  network = None

  # Full connected layer
  network = None

  # Dropout
  network = None

  # Full connected layer
  network = None

  network = regression(network, optimizer='adam', learning_rate=0.01,
                     loss=None, name='target')

  return network

## Task: train the model

Specify the training data

In [ ]:
network = cnn_model()

model = tflearn.DNN(network, tensorboard_verbose=0)

# Train the model
model.fit({'input': }, {'target': None}, n_epoch=2,
           snapshot_step=100, show_metric=True, run_id='convnet_mnist')

Training Step: 1719  | total loss: 0.08147 | time: 9.667s
| Adam | epoch: 002 | loss: 0.08147 - acc: 0.9754 -- iter: 54976/55000
Training Step: 1720  | total loss: 0.08211 | time: 9.677s
| Adam | epoch: 002 | loss: 0.08211 - acc: 0.9763 -- iter: 55000/55000
--


## Task: predicting on the test data

In [ ]:
model.predict(None)

array([[2.5345529e-12, 2.1529606e-11, 2.3361972e-07, ..., 9.9998868e-01,
        6.7699746e-10, 1.0787893e-05],
       [9.3582537e-09, 8.5420062e-09, 1.0000000e+00, ..., 1.5954961e-10,
        1.6524876e-10, 1.6200001e-14],
       [3.7454259e-07, 9.9913388e-01, 8.6052220e-05, ..., 6.9091046e-05,
        1.5892298e-04, 3.0028386e-06],
       ...,
       [2.3469557e-15, 3.5010933e-10, 5.6509662e-12, ..., 9.2003044e-11,
        6.2681216e-10, 3.6527897e-06],
       [4.8180826e-10, 7.4064666e-10, 1.0247285e-13, ..., 5.6973933e-11,
        9.5605265e-06, 3.1222847e-10],
       [1.6138503e-05, 2.4989856e-06, 3.7305168e-09, ..., 1.5022507e-13,
        1.7038620e-07, 1.3160183e-11]], dtype=float32)

## Predicting in a single example.

Try and make sense of the following by breaking down the function into smaller chunks

In [ ]:
np.argmax(model.predict(np.reshape(testX[0],(1, 28,28,1))),axis=1)

array([7])

## Predicting on all the test data and convert the output to labels

In [ ]:
predictions_testX = np.argmax(model.predict(np.reshape(testX,(-1, 28,28,1))),axis=1)

## Take a look at the first 5 predictions and the first 5 correct values

In [ ]:
predictions_testX[0:5]

array([7, 2, 1, 0, 4])

In [ ]:
correct_values = np.argmax(testY, axis=1)

In [ ]:
correct_values[0:5]

array([7, 2, 1, 0, 4])

## Display a confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(correct_values, predictions_testX)

array([[ 972,    0,    3,    1,    0,    0,    2,    1,    1,    0],
       [   0, 1121,    3,    0,    3,    0,    1,    6,    1,    0],
       [   0,    0, 1014,    3,    0,    0,    1,   13,    1,    0],
       [   0,    0,    0,  996,    0,    9,    0,    4,    1,    0],
       [   0,    2,    2,    0,  957,    0,    2,    6,    1,   12],
       [   2,    0,    0,    2,    0,  882,    1,    1,    2,    2],
       [   6,    5,    1,    0,    1,    3,  934,    0,    8,    0],
       [   0,    1,    1,    2,    0,    0,    0, 1021,    0,    3],
       [   2,    1,    1,    3,    1,    1,    0,    3,  961,    1],
       [   0,    0,    0,    1,    5,    3,    0,    4,    5,  991]])

Information about confusion matrix is available here: http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html#sphx-glr-auto-examples-model-selection-plot-confusion-matrix-py